// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IngredientInput struct {
	Name     string         `json:"name"`
	Quantity *QuantityInput `json:"quantity"`
}

type Mutation struct {
}

type Quantity struct {
	ID     int     `json:"id"`
	Unit   string  `json:"unit"`
	Amount float64 `json:"amount"`
}

type QuantityInput struct {
	Unit   string  `json:"unit"`
	Amount float64 `json:"amount"`
}

type Query struct {
}

type RecipeInput struct {
	Name        string             `json:"name"`
	Description *string            `json:"description,omitempty"`
	Ingredients []*IngredientInput `json:"ingredients,omitempty"`
	Steps       []*StepInput       `json:"steps,omitempty"`
}

type Step struct {
	ID          int    `json:"id"`
	Description string `json:"description"`
}

type StepInput struct {
	Description string `json:"description"`
}
